[package]
name = "validate-waveforms"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]

[[bin]]
name = "validate-waveforms"
path = "src/main.rs"

[dependencies]
wellen = { git = "https://github.com/MartinKavik/wellen", rev = "75de70c7e737432feacf91f8e803bfd62dccd39c" }
colored = "2"
